test

diff --git a/.github/workflows/deploy-to-dev.yaml b/.github/workflows/deploy-to-dev.yaml
--- a/.github/workflows/deploy-to-dev.yaml
+++ b/.github/workflows/deploy-to-dev.yaml
@@ -1,33 +1,57 @@
-# name: Deploy Calcom Stack To Dev
-
-# on:
-#   workflow_dispatch:
-# jobs:
-#   Deploy-Calcom-Stack:
+name: Deploy Calcom Stack To Dev
+on:
+  workflow_run:
+    workflows: ["Build and push image to DockerHub"]
+    branches: [main]
+    types:
+      - completed
+jobs:
+  Deploy-Calcom-Stack:
   
-#     runs-on: ubuntu-latest
-#     environment: Dev
-#     steps:
-#     - name: checkout
-#       uses: actions/checkout@v4
+    runs-on: ubuntu-latest
+    environment: Dev
+    steps:
+    - name: checkout
+      uses: actions/checkout@v4
 
-#     - name: Rsync Deployments
-#       uses: burnett01/rsync-deployments@7.0.1
-#       with:
-#         switches: -avzr --delete
-#         remote_path: /home/ubuntu/calcom
-#         remote_host: ${{ secrets.REMOTE_HOST }}
-#         remote_user: ${{ secrets.REMOTE_USER }}
-#         remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
+    - name: Rsync Deployments
+      uses: burnett01/rsync-deployments@7.0.1
+      with:
+        switches: -avzr --delete
+        remote_path: /home/ubuntu/calcom
+        remote_host: ${{ secrets.REMOTE_HOST }}
+        remote_user: ${{ secrets.REMOTE_USER }}
+        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
     
-#     - name: Run Docker Script
-#       uses: appleboy/ssh-action@v1.0.3
-#       with:
-#           host: ${{ secrets.REMOTE_HOST }}
-#           username: ${{ secrets.REMOTE_USER }}
-#           key: ${{ secrets.SSH_PRIVATE_KEY }}
-#           script: |
-#            sudo docker network create stack
-#            chmod +x /home/ubuntu/calcom/scripts/deploy.sh
-#            sudo bash /home/ubuntu/calcom/scripts/deploy.sh
+    - name: Install Docker
+      uses: appleboy/ssh-action@v1.0.3
+      with:
+        host: ${{ secrets.REMOTE_HOST }}
+        username: ${{ secrets.REMOTE_USER }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        script: |          
+          if ! command -v docker &> /dev/null; then
+            echo "Docker is not installed. Installing Docker..."
+            curl -fsSL https://get.docker.com | bash -
+          else
+            echo "Docker is already installed."
+          fi
+          # Check Docker version
+          docker --version
+          # Check docker-compose version
+          docker compose version
+    
+    # - name: Depoy Calcom Stack
+    #   uses: appleboy/ssh-action@v1.0.3
+    #   with:
+    #       host: ${{ secrets.REMOTE_HOST }}
+    #       username: ${{ secrets.REMOTE_USER }}
+    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
+    #       script: |
+    #         cd calcom
+    #         echo "Stopping and removing existing docker-compose containers..."
+    #         docker compose down || true  # Continue on error (if no containers are running)
+    #         echo "Starting docker-compose..."
+    #         docker compose -f docker-compose-prod.yaml up -d
+    
     
